# -*- coding: utf-8 -*-
"""cm_content_0928.py -- missing Description and "Listen for" text on active Classical Music cards.

Carter, 2026-09-28: "Some tier 1 cards missing description/listen for, eg. die schöpfung";
"Waldstein ... there's no listen for section".

133 active works had no Description and 328 active movement notes had no Listen. Written here by
hand, one line per work and per clip. Facts are the standard, checkable ones (premieres,
dedicatees, sources, famous features). A Listen line describes what the clip plays; where a clip is
not identified by its movement, it describes what holds for the whole piece rather than guessing
at a passage. Hamlet (Ambroise Thomas) is left without a Listen line because its clip could not
be identified.

"Organ Symphony" (Saint-Saëns) is a duplicate of the "Symphony No. 3" notes; its two notes are
suspended and tagged Music::dupe-suspended rather than given text.

Only empty fields are filled; nothing already written is overwritten.

    py -3.9 cm_content_0928.py [--apply]
"""
import json, sys, time
import concept_add as C

I = lambda t: "<i>%s</i>" % t

DESC = {
    ("Billy the Kid", "Aaron Copland"): "Written for Lincoln Kirstein's Ballet Caravan and choreographed by Eugene Loring, it quotes cowboy songs such as “Git Along, Little Dogies”; Billy is finally shot by Pat Garrett.",
    ("Lincoln Portrait", "Aaron Copland"): "A narrator reads from Lincoln's speeches and letters, ending with the Gettysburg Address, over music that quotes “Camptown Races” and the folk song “Springfield Mountain”.",
    ("Rodeo", "Aaron Copland"): "Composed for Agnes de Mille's ballet about a cowgirl trying to win the Head Wrangler; its “Hoedown” is built on the fiddle tune “Bonyparte”.",
    ("Lulu", "Alban Berg"): "Berg's second opera, after Frank Wedekind's Lulu plays; he died leaving the third act unorchestrated, and Friedrich Cerha completed it in 1979. Lulu ends murdered by Jack the Ripper.",
    ("Violin Concerto", "Alban Berg"): "Dedicated “to the memory of an angel”, Manon Gropius, the daughter of Alma Mahler, who died at eighteen; its tone row ends with the rising whole tones of Bach's chorale “Es ist genug”, which is quoted in the finale.",
    ("Wozzeck", "Alban Berg"): "After Georg Büchner's play " + I("Woyzeck") + ": a poor soldier, bullied by his Captain and experimented on by a Doctor, murders his lover Marie. Every scene is built on a closed form, such as a passacaglia or a suite.",
    ("Prince Igor", "Alexander Borodin"): "Left unfinished at Borodin's death and completed by Nikolai Rimsky-Korsakov and Alexander Glazunov; its Polovtsian Dances later supplied “Stranger in Paradise” to the musical " + I("Kismet") + ".",
    ("Prometheus", "Alexander Scriabin"): "Subtitled “The Poem of Fire”, it is scored for a colour organ (" + I("luce") + ") meant to bathe the hall in light, and it is built on Scriabin's “mystic chord” of stacked fourths.",
    ("Hamlet", "Ambroise Thomas"): "A French grand opera in which Hamlet survives to be crowned; Ophelia's mad scene is its coloratura showpiece, and it was among the first operas to use a saxophone.",
    ("Symphony No. 4", "Anton Bruckner"): "Bruckner gave it its nickname himself. It opens with a horn call over hushed string tremolo, and the scherzo of the 1878 revision is a hunting scene.",
    ("Te Deum", "Anton Bruckner"): "Bruckner called it the pride of his life and suggested it as a finale for his unfinished Ninth Symphony; it opens with a relentless C-major string figure under the choir's unison “Te Deum laudamus”.",
    ("L'estro armonico", "Antonio Vivaldi"): "Twelve concertos for one, two, and four violins, published in Amsterdam in 1711; they made Vivaldi famous across Europe, and Bach arranged several for keyboard.",
    ("Slavonic Dances", "Antonín Dvořák"): "Written for piano duet and then orchestrated, at Brahms's suggestion, for his publisher Fritz Simrock after the success of Brahms's Hungarian Dances; the first set made Dvořák's name.",
    ("Gayane", "Aram Khachaturian"): "A Soviet ballet set on an Armenian collective farm; its “Sabre Dance” became a worldwide hit, and its Adagio was used in Stanley Kubrick's " + I("2001: A Space Odyssey") + ".",
    ("Concerti grossi", "Arcangelo Corelli"): "Twelve concertos, published in 1714 after Corelli's death, that set a " + I("concertino") + " of two violins and cello against the full " + I("ripieno") + "; No. 8 is the “Christmas” Concerto.",
    ("Pierrot lunaire", "Arnold Schoenberg"): "Twenty-one poems by Albert Giraud, in German translation, set for a reciter in " + I("Sprechstimme") + " and five players; its ensemble of flute, clarinet, violin, cello, and piano is now called a “Pierrot ensemble”.",
    ("Verklärte Nacht", "Arnold Schoenberg"): "A string sextet after a poem by Richard Dehmel, in which a woman confesses on a moonlit walk that she carries another man's child, and her lover forgives her.",
    ("Má vlast", "Bedřich Smetana"): "Six tone poems on Bohemian history and landscape, from the castle of Vyšehrad to the Hussite mountain of Blaník; “Vltava” follows the river from its two springs through Prague. Smetana wrote them after going deaf.",
    ("The Bartered Bride", "Bedřich Smetana"): "The Czech national comic opera: Mařenka is promised to the simple-minded Vašek, but her beloved Jeník outwits the marriage broker Kecal.",
    ("Peter Grimes", "Benjamin Britten"): "After George Crabbe's poem " + I("The Borough") + ", about a Suffolk fisherman suspected in the deaths of his apprentices; its Four Sea Interludes are often played on their own. The 1945 premiere revived English opera.",
    ("Mikrokosmos", "Béla Bartók"): "153 progressive piano pieces in six books, from beginner exercises to concert pieces such as the Six Dances in Bulgarian Rhythm that close the last volume.",
    ("Der Freischütz", "Carl Maria von Weber"): "The founding German Romantic opera: the huntsman Max casts magic bullets in the Wolf's Glen to win a shooting contest and Agathe's hand. The Wolf's Glen scene is the model of " + I("melodrama") + ".",
    ("Invitation to the Dance", "Carl Maria von Weber"): "A piano rondo that frames a waltz with a dialogue between a gentleman and a lady; Berlioz orchestrated it, and it became the music of the ballet " + I("Le Spectre de la rose") + ".",
    ("Symphony No. 4", "Carl Nielsen"): "Nielsen said its title stands for the elemental will to live; in the finale two sets of timpani, on opposite sides of the orchestra, duel.",
    ("Piano Sonata No. 2", "Charles Ives"): "Each movement portrays Concord Transcendentalists: “Emerson”, “Hawthorne”, “The Alcotts”, and “Thoreau”. One passage calls for a board to press down clusters, and the opening motif of Beethoven's Fifth recurs throughout.",
    ("Three Places in New England", "Charles Ives"): "An orchestral set: the Saint-Gaudens memorial to the Black 54th Massachusetts regiment, “Putnam's Camp”, where two marching bands collide, and “The Housatonic at Stockbridge”.",
    ("Orfeo ed Euridice", "Christoph Willibald Gluck"): "Gluck's first “reform” opera, with the librettist Ranieri de' Calzabigi, stripping away " + I("da capo") + " display in favour of the drama; Orfeo was written for the castrato Gaetano Guadagni.",
    ("Children's Corner", "Claude Debussy"): "Six pieces with English titles for Debussy's daughter Chouchou; “Golliwogg's Cakewalk” mocks the opening of Wagner's " + I("Tristan und Isolde") + ".",
    ("Pelléas et Mélisande", "Claude Debussy"): "Debussy's only completed opera, an almost word-for-word setting of Maurice Maeterlinck's Symbolist play; Golaud kills his half-brother Pelléas out of jealousy over Mélisande.",
    ("Suite Bergamasque", "Claude Debussy"): "Four pieces, Prélude, Menuet, Clair de lune, and Passepied; the third, named after a Paul Verlaine poem, is Debussy's most famous piano piece.",
    ("L'Orfeo", "Claudio Monteverdi"): "Among the first operas, premiered at the Mantuan court in 1607 with a libretto by Alessandro Striggio; it opens with a trumpet toccata, and Orfeo's plea “Possente spirto” lulls the ferryman Charon.",
    ("L'incoronazione di Poppea", "Claudio Monteverdi"): "Monteverdi's last opera, in which Nero's scheming mistress Poppea becomes empress while virtue goes unrewarded; its closing duet “Pur ti miro” may be by another composer.",
    ("Symphony", "César Franck"): "Franck's only symphony, in three movements bound by cyclic themes; the slow movement opens with a cor anglais melody over harp and plucked strings.",
    ("Violin Sonata", "César Franck"): "A wedding present for the violinist Eugène Ysaÿe, cyclic in form, whose finale is a strict canon between violin and piano.",
    ("Lady Macbeth of the Mtsensk District", "Dmitri Shostakovich"): "Katerina Izmailova, bored in a merchant's house, murders her father-in-law and husband for her lover. Stalin walked out in 1936, and " + I("Pravda") + " condemned it as “Muddle Instead of Music”.",
    ("Holberg Suite", "Edvard Grieg"): "Written for the bicentenary of the playwright Ludvig Holberg, it recasts Baroque dances, Praeludium, Sarabande, Gavotte, Air, and Rigaudon, in Romantic string writing.",
    ("Piano Concerto", "Edvard Grieg"): "Grieg's only concerto; it opens with a timpani roll and the piano crashing down the keyboard, and Liszt played it at sight from the manuscript.",
    ("Cello Concerto", "Edward Elgar"): "An elegiac work written after the First World War; Jacqueline du Pré's 1965 recording made it famous. It opens with a recitative of chords from the soloist.",
    ("The Dream of Gerontius", "Edward Elgar"): "A setting of John Henry Newman's poem following a soul from its deathbed to judgment; a disastrous 1900 Birmingham premiere did not stop it becoming an English choral staple.",
    ("Gnossiennes", "Erik Satie"): "Slow, meandering piano pieces written without bar lines or time signatures, with whimsical directions to the player such as " + I("très luisant") + " (“very shiny”).",
    ("String Octet", "Felix Mendelssohn"): "Written at sixteen for a double string quartet treated as one orchestra; its gossamer scherzo was inspired by the Walpurgis Night in Goethe's " + I("Faust") + ".",
    ("Mazeppa", "Franz Liszt"): "After Victor Hugo's poem about the Cossack hetman tied to a wild horse and carried across the steppes; Liszt reworked it from his Transcendental Étude of the same name.",
    ("Gretchen am Spinnrade", "Franz Schubert"): "Written at seventeen, a scene from Goethe's " + I("Faust") + ": the piano's whirring right hand is the spinning wheel, which stops when Gretchen remembers Faust's kiss.",
    ("String Quartet No. 13", "Franz Schubert"): "The slow movement borrows an entr'acte from Schubert's incidental music to " + I("Rosamunde") + ", which gives the quartet its name; it was the only one of his quartets published in his lifetime.",
    ("Fantaisie-Impromptu", "Frédéric Chopin"): "Published after Chopin's death against his wishes; its lyrical middle section became the popular song “I'm Always Chasing Rainbows”.",
    ("Preludes", "Frédéric Chopin"): "Twenty-four short pieces, one in every major and minor key in circle-of-fifths order, finished in Majorca; No. 15 is the “Raindrop”.",
    ("Pavane", "Gabriel Fauré"): "Modelled on the slow Spanish court dance, with an optional chorus added later; its flute melody over plucked strings is Fauré's best-known tune.",
    ("L'elisir d'amore", "Gaetano Donizetti"): "A comic opera in which the poor Nemorino buys a fake love potion from the quack Dulcamara to win Adina; “Una furtiva lagrima” is its famous tenor aria.",
    ("Giulio Cesare", "George Frideric Handel"): "Handel's most successful opera for London, on Caesar and Cleopatra in Egypt; the castrato Senesino created Caesar, and Cleopatra seduces him with the aria “V'adoro, pupille”.",
    ("Porgy and Bess", "George Gershwin"): "An “American folk opera” after DuBose Heyward's novel " + I("Porgy") + ", set in Catfish Row in Charleston with an all-Black cast; “Summertime” is Clara's lullaby.",
    ("La fanciulla del West", "Giacomo Puccini"): "Set in a California gold-rush camp, after David Belasco's play, it premiered at the Metropolitan Opera in 1910 with Enrico Caruso; Minnie wins the bandit Dick Johnson's life in a poker game.",
    ("Amahl and the Night Visitors", "Gian Carlo Menotti"): "The first opera written for American television, broadcast by NBC on Christmas Eve 1951; a disabled shepherd boy offers his crutch to the Three Kings and is healed.",
    ("Nabucco", "Giuseppe Verdi"): "Verdi's first great success, on the Hebrews' captivity in Babylon; the chorus “Va, pensiero” became an anthem of Italian unification.",
    ("Otello", "Giuseppe Verdi"): "Verdi's penultimate opera, after Shakespeare, with a libretto by Arrigo Boito; Iago's “Credo” is Boito's invention, not Shakespeare's.",
    ("Das Lied von der Erde", "Gustav Mahler"): "A symphony in six songs for tenor and alto on Chinese poems in Hans Bethge's German versions; Mahler avoided numbering it as his Ninth, and it ends on the repeated word “ewig”.",
    ("Kindertotenlieder", "Gustav Mahler"): "Five songs on Friedrich Rückert's poems on the deaths of his children; Mahler's own elder daughter died a few years after he wrote them.",
    ("Symphony No. 4", "Gustav Mahler"): "The lightest of Mahler's symphonies: the finale sets a " + I("Wunderhorn") + " song that describes heaven through a child's eyes, and the scherzo's solo violin is tuned a tone high to play Death's fiddle.",
    ("Atmosphères", "György Ligeti"): "An orchestral piece with no melody or rhythm, only shifting clusters of sound; Stanley Kubrick used it without permission in " + I("2001: A Space Odyssey") + ".",
    ("Lux Aeterna", "György Ligeti"): "Sixteen unaccompanied voices in slowly shifting clusters, the technique Ligeti called micropolyphony; like " + I("Atmosphères") + ", it was used in " + I("2001: A Space Odyssey") + ".",
    ("Études", "György Ligeti"): "Three books of fiendish piano études shaped by Conlon Nancarrow's player-piano rhythms and African polyrhythm; titles include “Désordre” and “L'escalier du diable”.",
    ("Palestrina", "Hans Pfitzner"): "A “musical legend” in which the Renaissance composer saves church polyphony by writing the " + I("Pope Marcellus Mass") + ", dictated to him by angels.",
    ("Dido and Aeneas", "Henry Purcell"): "Purcell's only true opera, with a libretto by Nahum Tate, perhaps first given at a girls' school in Chelsea; Dido's Lament is sung over a descending chromatic ground bass.",
    ("Symphony of Psalms", "Igor Stravinsky"): "Written for the Boston Symphony's fiftieth anniversary, it sets Latin psalms for chorus and an orchestra with no violins, violas, or clarinets.",
    ("Orpheus in the Underworld", "Jacques Offenbach"): "Offenbach's parody of the Orpheus myth and of Second Empire society; its “Infernal Galop” is the tune of the can-can.",
    ("The Tales of Hoffmann", "Jacques Offenbach"): "Offenbach's last work, left unfinished at his death: the poet Hoffmann tells of three lost loves, the doll Olympia, the singer Antonia, and the courtesan Giulietta.",
    ("The Swan of Tuonela", "Jean Sibelius"): "One of the four Lemminkäinen Legends from the " + I("Kalevala") + ": a swan glides on the black river around the land of the dead, voiced by a cor anglais.",
    ("Violin Concerto", "Jean Sibelius"): "Sibelius's only concerto, revised in 1905; the soloist enters over hushed, divided violins, and Donald Tovey called the finale a “polonaise for polar bears”.",
    ("Canon in D", "Johann Pachelbel"): "Three violins in canon over a two-bar ground bass repeated twenty-eight times; long forgotten, it became a wedding staple after a 1968 recording.",
    ("Coffee Cantata", "Johann Sebastian Bach"): "A comic secular cantata first performed at Zimmermann's coffee house in Leipzig: a father tries to cure his daughter Lieschen of her coffee habit.",
    ("Mass in B minor", "Johann Sebastian Bach"): "Assembled late in Bach's life, largely from earlier music, it is a Lutheran composer's complete setting of the Catholic Ordinary; it was never performed complete in his lifetime.",
    ("St. Matthew Passion", "Johann Sebastian Bach"): "Written for Good Friday in Leipzig for double choir and double orchestra; Mendelssohn's 1829 revival launched the modern Bach revival, and the chorale “O Sacred Head” recurs five times.",
    ("The Art of Fugue", "Johann Sebastian Bach"): "Fourteen fugues and four canons on one subject, left unfinished at Bach's death; the last fugue breaks off soon after the B–A–C–H motif enters.",
    ("The Musical Offering", "Johann Sebastian Bach"): "Written on a theme that Frederick the Great gave Bach at Potsdam in 1747; it contains two ricercars, ten canons, and a trio sonata with flute for the flute-playing king.",
    ("Well-Tempered Clavier", "Johann Sebastian Bach"): "Two books of preludes and fugues in all twenty-four major and minor keys; the C-major prelude of Book I underlies Charles Gounod's “Ave Maria”.",
    ("Die Fledermaus", "Johann Strauss II"): "Strauss's most famous operetta: Eisenstein and his wife each go masked to Prince Orlofsky's ball, where Dr. Falke takes revenge for an old prank.",
    ("Lullaby", "Johannes Brahms"): "Written for the birth of a son to Bertha Faber, a singer Brahms had known in Hamburg; its German text begins “Guten Abend, gut' Nacht”.",
    ("Nixon in China", "John Adams"): "On Richard Nixon's 1972 visit to Mao, with a libretto by Alice Goodman and direction by Peter Sellars; Nixon sings “News has a kind of mystery” as he steps off Air Force One.",
    ("Short Ride in a Fast Machine", "John Adams"): "A four-minute fanfare over a relentless woodblock pulse; Adams likened it to a ride in a terrific sports car that you wish you hadn't taken.",
    ("Die Jahreszeiten", "Joseph Haydn"): "Haydn's second great oratorio, after James Thomson's poem " + I("The Seasons") + ", following country life through the year; Haydn himself found some of its nature painting trivial.",
    ("Die Schöpfung", "Joseph Haydn"): "An oratorio on Genesis and " + I("Paradise Lost") + ", inspired by the Handel oratorios Haydn heard in London; it opens with “The Representation of Chaos”, and a blazing C-major chord answers “and there was light”.",
    ("Thaïs", "Jules Massenet"): "An Alexandrian courtesan is converted by a monk who then falls in love with her; the violin “Méditation” is the interlude between her conversion scenes.",
    ("Candide", "Leonard Bernstein"): "Bernstein's operetta on Voltaire's satire, with lyrics by Richard Wilbur and others; Cunegonde's aria “Glitter and Be Gay” parodies the coloratura showpiece.",
    ("Sinfonietta", "Leoš Janáček"): "Dedicated to the Czechoslovak armed forces and scored with fourteen trumpets among its extra brass; its movements portray places in his home city of Brno.",
    ("Fidelio", "Ludwig van Beethoven"): "Beethoven's only opera: Leonore disguises herself as a young man, Fidelio, to rescue her husband Florestan from a political prison. He wrote four overtures for it.",
    ("Grosse Fuge", "Ludwig van Beethoven"): "Written as the finale of the String Quartet Op. 130, but so difficult that his publisher persuaded Beethoven to replace it; Stravinsky called it “an absolutely contemporary piece of music that will be contemporary forever”.",
    ("Piano Sonata No. 29", "Ludwig van Beethoven"): "Beethoven's longest piano sonata, written for the newer, sturdier pianos; it ends with a vast three-voice fugue marked “with some liberties”.",
    ("Violin Sonata No. 9", "Ludwig van Beethoven"): "Written for the violinist George Bridgetower but dedicated to Rodolphe Kreutzer, who never played it; it gave Leo Tolstoy the title of a novella.",
    ("Lakmé", "Léo Delibes"): "Set in British India: a Brahmin priest's daughter falls in love with a British officer. The Flower Duet and the Bell Song are its famous numbers.",
    ("Gaspard de la nuit", "Maurice Ravel"): "Three poems by Aloysius Bertrand: the water nymph Ondine, a hanged man on the gallows, and the goblin Scarbo, which Ravel meant to be harder than Balakirev's " + I("Islamey") + ".",
    ("Le tombeau de Couperin", "Maurice Ravel"): "A suite in Baroque forms whose movements are each dedicated to a friend killed in the First World War; Ravel orchestrated four of its six movements.",
    ("Pavane pour une infante défunte", "Maurice Ravel"): "An early piano piece that Ravel later orchestrated; he said he chose the title for its sound, not for any dead princess.",
    ("Boris Godunov", "Modest Mussorgsky"): "After Pushkin: the tsar, haunted by the murdered heir Dmitri, faces a Pretender claiming to be him. It is best known in Rimsky-Korsakov's reorchestration.",
    ("24 Caprices for Solo Violin", "Niccolò Paganini"): "The touchstone of violin virtuosity; the theme of No. 24 has been varied by Brahms, Liszt, Rachmaninoff, and Witold Lutosławski.",
    ("Capriccio espagnol", "Nikolai Rimsky-Korsakov"): "A showcase of orchestral virtuosity on Spanish themes, dedicated to the sixty-seven players of its premiere, whose names Rimsky-Korsakov wrote into the score.",
    ("Russian Easter Festival Overture", "Nikolai Rimsky-Korsakov"): "Built on Russian Orthodox chants, moving from the solemnity of Holy Week to the bells and rejoicing of Easter morning.",
    ("The Tale of Tsar Saltan", "Nikolai Rimsky-Korsakov"): "After Pushkin's fairy tale; Prince Gvidon is turned into a bumblebee to visit his father, which is the scene of “Flight of the Bumblebee”.",
    ("Quartet for the End of Time", "Olivier Messiaen"): "Composed in a German prisoner-of-war camp and first played there in January 1941, for the only instruments at hand: violin, clarinet, cello, and piano.",
    ("Pines of Rome", "Ottorino Respighi"): "Four scenes of Rome's pine trees; the third calls for a recording of a nightingale, and the last marches a Roman legion up the Appian Way.",
    ("The Sorcerer's Apprentice", "Paul Dukas"): "After Goethe's ballad about a boy who enchants a broom to fetch water and cannot stop it; Mickey Mouse plays the apprentice in Disney's " + I("Fantasia") + ".",
    ("Einstein on the Beach", "Philip Glass"): "A four-and-a-half-hour opera by Philip Glass and Robert Wilson with no plot, linked by five “Knee Plays”; the text is numbers, solfège syllables, and spoken fragments.",
    ("Eugene Onegin", "Pyotr Ilyich Tchaikovsky"): "After Pushkin's verse novel: Onegin rejects Tatiana's letter, kills his friend Lensky in a duel, and years later is rejected by her in turn.",
    ("Marche slave", "Pyotr Ilyich Tchaikovsky"): "Written for a concert for Serbian soldiers wounded fighting the Ottoman Turks, it quotes Serbian folk songs and the Russian imperial anthem “God Save the Tsar”.",
    ("A Sea Symphony", "Ralph Vaughan Williams"): "Vaughan Williams's first symphony, for soloists, chorus, and orchestra, on poems by Walt Whitman; it opens with the chorus crying “Behold, the sea itself”.",
    ("Fantasia on a Theme by Thomas Tallis", "Ralph Vaughan Williams"): "For a string quartet and two string orchestras of different sizes, on a psalm tune by Thomas Tallis; it premiered in Gloucester Cathedral in 1910.",
    ("Adagio", "Remo Giazotto (attributed to Tomaso Albinoni)"): "Presented by Remo Giazotto as a reconstruction of a fragment by Tomaso Albinoni, but almost certainly Giazotto's own composition.",
    ("Ein Heldenleben", "Richard Strauss"): "A tone poem whose hero is Strauss himself: his critics chatter in the woodwinds, his wife Pauline is a solo violin, and he quotes his own earlier works.",
    ("Elektra", "Richard Strauss"): "Strauss's first opera with Hugo von Hofmannsthal, after Sophocles: Elektra waits to avenge her father Agamemnon, and the recognition of her brother Orest is its emotional heart.",
    ("Das Rheingold", "Richard Wagner"): "The prologue to Wagner's Ring: Alberich steals the Rhine gold and forges the ring, which Wotan takes from him. It opens on an E-flat chord held for 136 bars.",
    ("Die Meistersinger von Nürnberg", "Richard Wagner"): "Wagner's only mature comedy: the knight Walther wins the song contest and Eva's hand with the cobbler Hans Sachs's help, while the pedant Beckmesser caricatures the critic Eduard Hanslick.",
    ("Die Walküre", "Richard Wagner"): "The second part of the Ring: the twins Siegmund and Sieglinde fall in love, and Wotan punishes his daughter Brünnhilde by putting her to sleep inside a ring of fire. Act III opens with the Ride of the Valkyries.",
    ("Götterdämmerung", "Richard Wagner"): "The last part of the Ring: Hagen murders Siegfried, and Brünnhilde rides into his funeral pyre as the Rhine overflows and Valhalla burns.",
    ("Parsifal", "Richard Wagner"): "Wagner's last opera, a “festival play for the consecration of the stage”: the innocent fool Parsifal heals the wounded Grail king Amfortas. Bayreuth long kept it to itself.",
    ("Rienzi", "Richard Wagner"): "Wagner's early grand opera on the Roman tribune Cola di Rienzi; its 1842 success in Dresden launched his career.",
    ("Siegfried", "Richard Wagner"): "The third part of the Ring: Siegfried reforges the sword Nothung, kills the dragon Fafner, and wakes Brünnhilde on her fiery rock.",
    ("The Ring Cycle", "Richard Wagner"): "Four operas on the curse of a ring forged from the Rhine gold, woven from leitmotifs; the whole cycle was first staged at Wagner's Bayreuth Festspielhaus in 1876.",
    ("Carnaval", "Robert Schumann"): "Twenty-one short pieces portraying masked revellers, friends such as Chopin and Paganini, and Schumann's own two sides, Florestan and Eusebius; most are built on the letters A–S–C–H.",
    ("Dichterliebe", "Robert Schumann"): "Sixteen songs to Heinrich Heine's poems, tracing a love affair to its bitter end; “Ich grolle nicht” is the defiant climax.",
    ("Kinderszenen", "Robert Schumann"): "Thirteen short “scenes from childhood”, written for adults to hear; the seventh, “Träumerei”, is the most famous.",
    ("Kreisleriana", "Robert Schumann"): "Eight fantasies named after E. T. A. Hoffmann's mad bandmaster Johannes Kreisler and dedicated to Chopin; Schumann wrote them in a few days while in love with Clara Wieck.",
    ("Papillons", "Robert Schumann"): "Schumann's Op. 2, twelve short dances imagining the masked ball in Jean Paul's novel " + I("Flegeljahre") + "; a clock striking six ends the ball.",
    ("Adagio for Strings", "Samuel Barber"): "Arranged from the slow movement of Barber's String Quartet; Arturo Toscanini premiered it in a 1938 radio broadcast, and it has become the standard music of American national mourning.",
    ("Knoxville: Summer of 1915", "Samuel Barber"): "A setting for soprano of James Agee's prose-poem about a summer evening in his childhood, later the prologue to his novel " + I("A Death in the Family") + ".",
    ("Cinderella", "Sergei Prokofiev"): "Prokofiev's second full-length ballet, finished after the war; the clock striking midnight is its famous orchestral effect.",
    ("The Love for Three Oranges", "Sergei Prokofiev"): "After Carlo Gozzi's fairy-tale play: a prince cursed to love three oranges must find them. Its March became a concert favourite.",
    ("Isle of the Dead", "Sergei Rachmaninoff"): "Inspired by a black-and-white reproduction of Arnold Böcklin's painting; it moves in 5/8 like the strokes of an oar and quotes the " + I("Dies irae") + ".",
    ("Rhapsody on a Theme of Paganini", "Sergei Rachmaninoff"): "Twenty-four variations for piano and orchestra on Paganini's 24th Caprice; the eighteenth turns the theme upside down into a lush melody.",
    ("In C", "Terry Riley"): "Fifty-three short figures that any number of players repeat at their own pace over a steady pulse of Cs on the piano; its 1964 premiere launched minimalism.",
    ("Norma", "Vincenzo Bellini"): "Bellini's masterpiece: a Druid priestess has secretly borne the Roman proconsul two children. “Casta diva” is the model of " + I("bel canto") + " melody.",
    ("Così fan tutte", "Wolfgang Amadeus Mozart"): "The third Mozart–Da Ponte opera: two officers, on a bet with the cynic Don Alfonso, test their fiancées' fidelity in disguise.",
    ("Die Entführung aus dem Serail", "Wolfgang Amadeus Mozart"): "A " + I("Singspiel") + " in which Belmonte rescues Konstanze from the Pasha's harem; its “Turkish” janissary music uses triangle, cymbals, and bass drum, and the Pasha only speaks.",
    ("Piano Sonata No. 11", "Wolfgang Amadeus Mozart"): "Unusually, none of its movements is in sonata form: it opens with a theme and variations and ends with the “Rondo alla turca”, imitating a janissary band.",
    ("Symphonie espagnole", "Édouard Lalo"): "Despite its name, a five-movement violin concerto, written for Pablo de Sarasate; it helped start the French vogue for Spanish colour.",
}

LISTEN = {
    1787711405045: "The Shaker hymn “Simple Gifts” in the solo clarinet, stated plainly, then passed around the orchestra in a set of variations.",
    1788199514610: "Wide-spaced open fifths and fourths in woodwinds and strings, Copland's sound for the empty prairie, over a slow, plodding tread.",
    1787711405046: "Timpani and bass drum strokes, then the trumpets in unison on a rising line of open fourths and fifths; horns and trombones answer.",
    1788199514661: "A slow, dignified orchestral passage in dotted rhythms and open harmonies, before the narrator's first words.",
    1787711405047: "Strings and woodblock vamp a square-dance rhythm, then the fiddle tune bursts out in the violins.",
    1788199513971: "Dense twelve-tone writing that still sounds lush and late-Romantic, with alto saxophone and vibraphone in the orchestra.",
    1788199513970: "The soloist rocks across the violin's open strings in arpeggios, over harp and clarinets.",
    1788199513969: "Atonal, fragmentary orchestration with sharp contrasts, and voices that move between singing and speech-song.",
    1787711405033: "A slow, sinuous oboe melody over a rocking accompaniment, the tune later sung as “Stranger in Paradise”.",
    1787711405034: "Fast and savage: pounding accents as the orchestra and chorus whip up a wild dance.",
    1787711405638: "A hazy, sustained sonority built on the “mystic chord” of stacked fourths, with no clear key, in shimmering orchestral colour.",
    1788199512356: "A solo horn call over hushed string tremolo, the classic Bruckner opening out of silence.",
    1788199512401: "A pounding C-major string figure under the choir's bold unison “Te Deum laudamus”.",
    1788199511461: "Brilliant string ritornellos, with violins trading virtuoso solos over a harpsichord continuo.",
    1787711405371: "A quiet clarinet theme over low strings that builds to a full orchestral statement; the horn then sings the lyrical second theme.",
    1787711405375: "A gentle woodwind chorale, then the cello's tender melody; the stormy middle section quotes Dvořák's own song “Leave me alone”.",
    1788489953181: "Harp arpeggios shimmer before the soprano's long, floating melody addressed to the moon.",
    1787711405059: "A furious G-minor furiant for full orchestra, with accents shifting between groups of two and three.",
    1787711405379: "A fiery C-major furiant: stamping accents and quick switches between groupings of two and three.",
    1787711405381: "Shimmering strings, then the viola plays the pentatonic main theme.",
    1787711405382: "A melancholy, spiritual-like melody in the violin over a gently rocking accompaniment, later taken up by the cello.",
    1787711405091: "Hammering xylophone and snare drum over a relentless ostinato, with a broad saxophone and cello tune in the middle.",
    1787792906308: "Stately Italian string writing: a small group of two violins and cello alternates with the full string band.",
    1787792906335: "A voice half-speaking, half-singing in " + I("Sprechstimme") + " over a small ensemble of flute, clarinet, violin, cello, and piano.",
    1788199514062: "A dark, slowly descending D-minor line in the low strings, the couple walking through a cold moonlit wood.",
    1788489953178: "A string of bright Gilbert and Sullivan tunes, with a pseudo-Japanese flavour in the orchestration.",
    1788489953177: "The Sergeant and his police chorus sing a quaking march, punctuated by their comic “Tarantara!”.",
    1787711405164: "Two flutes ripple as the river's two springs, then the violins take up the flowing E-minor river theme.",
    1787792906328: "A breathless fugato for the strings racing in perpetual motion before the full orchestra enters.",
    1787792906349: "High violins and flutes over rippling harp and violas, with brass chords like breaking waves: a grey Suffolk dawn.",
    1788199514346: "Purcell's theme from " + I("Abdelazer") + " for full orchestra, then for each family of instruments in turn.",
    1788199514389: "Bells tolling on a tritone under a hushed chorus singing the Latin “Requiem aeternam”.",
    1788199513869: "Blazing full orchestra and organ in C major as Judith opens the door onto Bluebeard's vast domain.",
    1788199513819: "A brooding introduction in the low strings, with a flute line built on fourths, before the brisk Allegro.",
    1788199513870: "Short, crisp piano pieces built on folk modes and asymmetrical Bulgarian rhythms.",
    1787711405149: "Glassy runs on celesta or glass harmonica and two pianos over muted strings, fish gliding in a tank.",
    1787711405883: "The cello's long, gliding melody over rippling arpeggios from two pianos.",
    1787711405151: "The harp strikes twelve for midnight, then Death tunes his fiddle: the solo violin, its E string lowered to E-flat, plays a tritone.",
    1787711405153: "A restless C-minor scherzo, then the organ's thundering C-major chord launching the finale with orchestra and four-hand piano.",
    1787711405876: "Agitated strings in C minor, then, in the slow second half, the organ enters softly under a serene string melody.",
    1788199516777: "A slow dialogue, the gentleman asking in the left hand and the lady answering in the right, before the brilliant waltz.",
    1788199516698: "A turbulent, clashing outburst for full orchestra, then a gentle theme for two clarinets in thirds.",
    1788489953168: "Méphistophélès' swaggering bass song about the golden calf, over a rollicking, heavy-footed orchestra and chorus.",
    1788199514992: "Dense, dissonant piano writing out of which the four-note motif of Beethoven's Fifth keeps surfacing.",
    1788199514895: "Soft, sustained string chords like silence, a solo trumpet asking the same atonal question, and flutes answering with growing agitation.",
    1788199514943: "Layered textures quoting marches, hymns, and patriotic songs, sometimes in two tempos at once.",
    1787711406083: "Orfeo's lament for Euridice, a calm, almost major-key melody that returns like a refrain.",
    1787711406084: "Euridice's agitated pleading with Orfeo, who will not look at her.",
    1787711405785: "Running piano sixteenths parodying a Clementi finger exercise, which drifts off into daydreams.",
    1787711405786: "Syncopated cakewalk rhythms, interrupted by a sly quotation of the opening of " + I("Tristan und Isolde") + ".",
    1787711405794: "Hushed low strings and harp as the sea wakes at dawn, with muted trumpet and cor anglais sounding a motto theme.",
    1787711405795: "Sparkling, fragmented orchestration, harp glissandi, glockenspiel, and trills, as the waves play.",
    1787711405798: "Clarinets and bassoons in slow parallel chords and a haunting cor anglais motif: clouds drifting.",
    1787711405799: "Festive string triplets, then a distant procession of muted trumpets draws near.",
    1787711405801: "Hushed modal chords in the low strings and woodwinds, the music of the dark forest of Allemonde.",
    1787711405049: "A solo flute's languid chromatic melody, sliding down through a tritone, unaccompanied at first.",
    1787711405050: "Soft piano chords in D-flat major in a gently swaying 9/8.",
    1788199515491: "Orfeo's florid plea to Charon, each verse accompanied by different obbligato instruments.",
    1788199515538: "A sensuous duet in which two high voices intertwine over a repeating ground bass.",
    1787711405631: "Plucked strings and harp, then a melancholy cor anglais melody.",
    1787711405632: "A bright D-major theme in the cellos and bassoons; themes from earlier movements return in cyclic fashion.",
    1788199516274: "Gently rocking piano chords and a lilting violin melody, the cyclic theme that returns throughout.",
    1788199513274: "A massive orchestral passacaglia: a dark ground bass in low brass and strings building to crushing climaxes.",
    1787792906345: "A jagged canon between low and high strings on a dotted rhythm, then a long, bleak violin melody.",
    1787792906311: "A single-movement harpsichord sonata with a gently lilting, pastoral melody over a steady bass.",
    1788199516746: "Brisk, rippling Baroque-style string figures under a buoyant melody.",
    1787711405071: "A slow, mournful string lament in B minor, muted and hushed.",
    1787711405073: "A creeping theme in the bassoons and pizzicato basses, repeated faster and louder until it explodes.",
    1787711405075: "A pastoral flute melody answered by the oboe, rising to a sunrise in full strings.",
    1787711405601: "A timpani roll, then the piano's crashing chords cascade down the keyboard in A minor.",
    1787711405603: "A driving, dance-like theme in 2/4 on the rhythm of the Norwegian halling, with the piano leading.",
    1788199515205: "The cello's declamatory opening chords, then a sad, rocking 9/8 melody, first in the violas.",
    1788199515255: "A halting, melancholy G-minor melody in the strings, the theme on which every variation is built.",
    1787711405062: "A slow, noble E-flat melody in the strings that swells to a radiant climax; it portrays Elgar's publisher August Jaeger.",
    1787792906331: "Slow, chromatic themes for strings and woodwinds, full of Wagnerian yearning.",
    1788199516836: "A slow, meandering piano melody with a modal, exotic flavour over a plain repeated chord in the bass.",
    1787711405100: "A trumpet fanfare, then the full orchestra launches the C-major wedding march.",
    1787711405656: "A warm, slow melody for solo horn over soft strings and bassoons.",
    1787711405642: "A calm, consoling setting of Isaiah's promise that the Lord's kindness will not depart.",
    1787711405643: "Elijah's curse, sung before the overture: a solemn bass recitative over trombone chords, announcing the drought.",
    1787711405098: "A rolling B-minor figure in violas, cellos, and bassoons, the waves around Fingal's Cave.",
    1787711405648: "A brisk hunting song for piano, with horn-call figures in 6/8.",
    1787711405664: "The first violin soars on a rising arpeggio theme over shimmering tremolo from the other seven strings.",
    1787711405668: "Bright repeated chords in the woodwinds, then the violins leap into an exuberant A-major theme.",
    1787711405669: "A solemn, processional melody over a walking bass, like a line of pilgrims.",
    1787711405672: "After barely a bar, the soloist enters with the famous yearning E-minor melody high on the E string.",
    1787711405673: "A skittering, elfin finale in E major, with woodwinds calling and the soloist darting above.",
    1788489953211: "Hanna's wistful song about a forest sprite, with a hushed refrain that the chorus echoes.",
    1787711405613: "High, repeated bell notes in the right hand, with wide leaps across the keyboard.",
    1787711405618: "Galloping triplet rhythms across the full orchestra as Mazeppa's horse races over the steppes.",
    1787711405157: "A serene, rising vocal melody over gently rippling piano triplets.",
    1787711405517: "A bright strophic song whose piano imitates the turning of a mill wheel.",
    1787711405518: "A sad dialogue: the miller sings in G minor, and the brook answers him in a consoling G major.",
    1787711405521: "Pounding piano octaves for the galloping horse, with a menacing low figure in the left hand.",
    1787711405524: "A constant whirring figure in the piano, the spinning wheel, under Gretchen's anxious melody.",
    1787711405544: "A melancholy A-minor melody in the first violin over a murmuring second violin and a restless rhythm in the lower strings.",
    1787711405545: "A gentle C-major melody borrowed from Schubert's incidental music to " + I("Rosamunde") + ".",
    1787711405506: "A fierce D-minor unison outburst with a triplet figure, then hushed chords.",
    1787711405507: "Hushed, chorale-like chords from Schubert's song “Death and the Maiden”, the theme for a set of variations.",
    1787711405522: "Hammering long–short–short rhythms in C major, the rhythm of Schubert's song “Der Wanderer”.",
    1787711405523: "The song “Der Wanderer” itself, slow and sombre in C-sharp minor, as the theme for variations.",
    1787711405554: "A bare drone of open fifths and a looping hurdy-gurdy figure in the piano beneath a flat, weary vocal line.",
    1787711405555: "Rustling piano triplets, then a warm, folk-like melody about the linden tree.",
    1787711405567: "Rapid, rippling right-hand figures in fours against left-hand triplets.",
    1787711405037: "A slow march in B-flat minor over a tolling bass, one of the most recognizable dirges ever written.",
    1787792906323: "Short piano miniatures, each built on a single figure and mood.",
    1787711405043: "Stormy left-hand runs roaring under heroic octaves in the right hand.",
    1788199516364: "A slow, graceful flute melody over plucked strings in F-sharp minor.",
    1787792906329: "Hushed, restrained choral writing with organ and low strings: no " + I("Dies irae") + ", and a gentle, consoling tone.",
    1788199515398: "A bassoon introduces a melancholy tune before the tenor's tender aria.",
    1788489953149: "A jaunty military tenor aria famous for its nine high Cs.",
    1788199515350: "A flute, standing in for the glass harmonica, echoes the soprano's florid, fragmented coloratura as Lucia loses her mind.",
    1788199511994: "A French overture: stately dotted rhythms, then a quicker fugal section.",
    1787711405077: "English Baroque oratorio writing: clear choral textures over strings and continuo, with trumpets and timpani in the grand choruses.",
    1787711405078: "A jubilant D-major dance for trumpets, horns, and drums.",
    1787711405081: "Bold horn and trumpet calls answering the strings in a bright hornpipe.",
    1787792906310: "Bright Baroque dance music with horns and trumpets, written to be played outdoors.",
    1787711405083: "A long, hushed string introduction of rising arpeggios, then the choir's sudden, blazing entry on “Zadok the priest”.",
    1787711405066: "Jaunty walking themes and honking taxi horns, real ones written into the score.",
    1787711405068: "A clarinet trill and glissando swooping up to a jazzy melody.",
    1788199514801: "A slow, bluesy lullaby for soprano over a gently rocking accompaniment.",
    1787711405027: "A sultry mezzo-soprano melody that slides down chromatically over the habanera rhythm in the cellos.",
    1787711405029: "The brisk, festive march that opens the opera, with the Toreador's tune in its middle.",
    1788489953360: "Graceful, florid writing as Marguerite de Valois sings of her garden in Touraine.",
    1788489953370: "A big, sweeping Puccini orchestra with American touches, a minstrel song and whole-tone harmony, in a gold-rush saloon.",
    1787711405132: "The tenor's aria rising to its final “Vincerò!”, with an offstage chorus of women.",
    1787711405697: "Harsh, crashing chords and a Mandarin's proclamation, with Chinese melodies colouring the orchestra.",
    1788489953316: "A lively, folk-like dance in the woodwinds for the shepherds' visit.",
    1788489953140: "Cenerentola's final rondo: dazzling coloratura runs for mezzo-soprano.",
    1788489953141: "Two snare drum rolls, then a march, and one of Rossini's trademark crescendos.",
    1788489953338: "A brisk, light Italian overture for strings.",
    1787711405193: "The gypsies sing in rhythm while striking anvils.",
    1787711405766: "Leonora's aria about the calm night when she first heard the troubadour, followed by a brilliant cabaletta.",
    1787711405773: "The Hebrew slaves' chorus, sung mostly in unison, longing for their lost homeland.",
    1787711405774: "Iago's nihilistic creed, with snarling brass trills and violent orchestral outbursts.",
    1787711405086: "Bustling horns and strings, then the stately tune later sung as the hymn “I Vow to Thee, My Country”.",
    1787711405088: "Strings struck with the wood of the bow and timpani hammer out a relentless rhythm in 5/4.",
    1787792906327: "Pentatonic melodies and delicate, chamber-like orchestration evoking the Chinese poems.",
    1788199512222: "Spare, chamber-like orchestration and a restrained voice over bleak woodwind lines.",
    1788199512132: "The slow movement's sudden outburst: the full orchestra blazes in E major before fading back to calm.",
    1787711405096: "Strings and harp alone in a slow, rapturous F-major melody.",
    1788199512174: "A halting, irregular rhythm in the cellos and horn, then a sighing two-note figure in the violins.",
    1788199516863: "A vast, static cluster of chromatic notes, played softly by the whole orchestra, slowly shifting in colour.",
    1788199516864: "Unaccompanied voices on sustained, overlapping clusters that slowly shift.",
    1787792906363: "Fast, glittering piano patterns in overlapping rhythms that create illusory melodies.",
    1788489953210: "Post-Wagnerian orchestral writing with archaic, modal harmony that evokes Renaissance polyphony.",
    1787711405431: "A solo viola introduces Harold's melancholy theme over harp chords.",
    1787711405434: "A slow processional march, with the viola's Harold theme above it and a repeated bell-like note.",
    1787711405025: "Tolling bells and a grotesque version of the beloved's theme on E-flat clarinet, then the " + I("Dies irae") + " in tubas and bassoons.",
    1787711405457: "Timpani and pizzicato basses, then a descending march theme and blaring brass.",
    1787792906306: "A descending chromatic ground bass repeated beneath Dido's “When I am laid in earth”.",
    1787711405169: "Violent, irregularly accented chords whose metre changes almost every bar.",
    1787792906336: "Irregular, pounding accents and folk-like fragments in dissonant, primitivist orchestration.",
    1788199513596: "The bustle of the Shrovetide Fair: swirling flute and string figures, accordion-like harmonies, and Russian folk tunes.",
    1788199513637: "Stark, dry chords for winds and brass, with no violins or violas, under a Latin chorus.",
    1787711405168: "A soft horn melody, a Russian folk tune, repeated and building to a triumphant brass climax.",
    1787711405123: "Light, satirical operetta music, culminating in the galloping can-can.",
    1787711405124: "A slow introduction with a solo violin, then fast galop themes leading to the can-can.",
    1787711405125: "A gently rocking duet in 6/8 for soprano and mezzo-soprano, “Belle nuit, ô nuit d'amour”.",
    1788199512860: "A long cor anglais solo floating over divided, muted strings.",
    1788199512812: "The soloist enters over hushed, divided, muted violins.",
    1787711405127: "Three violins in canon over a two-bar ground bass that repeats throughout.",
    1787711405001: "A bright D-major ritornello for strings, with flute, violin, and harpsichord as soloists.",
    1788199511863: "A light, comic Baroque cantata, with arias for soprano and bass and a tenor narrator.",
    1788199511656: "The Aria: a slow, ornamented sarabande over the bass line that underlies all thirty variations.",
    1788199511557: "Massive Baroque choral writing in five parts over a full orchestra.",
    1787711405007: "A slow, sombre four-part Lutheran chorale in Bach's harmonization.",
    1787792906314: "An austere D-minor fugue subject stated alone, then answered in the other voices.",
    1788199511710: "The “Royal Theme”, a winding chromatic C-minor subject, woven into strict counterpoint.",
    1787711405008: "Organ flourishes in D minor, a plunging run, and a thundering diminished chord.",
    1787711405010: "Broken C-major chords in one unbroken, gently flowing pattern.",
    1787711405166: "A lilting waltz built on melodies from the operetta.",
    1787711405165: "Tremolo strings and a rising horn call, then the swaying D-major waltz.",
    1787711405276: "A hushed, mysterious opening before a sequence of student songs, ending with “Gaudeamus igitur”.",
    1787711405036: "The gentle, rocking melody of “Guten Abend, gut' Nacht”.",
    1787711405259: "A pounding timpani pedal under strings and winds straining in opposite directions.",
    1787711405261: "A graceful clarinet melody in A-flat major over pizzicato cellos.",
    1787711405272: "Horns and woodwinds in the Phrygian mode, then a hushed E-major string melody.",
    1787711405274: "Violins sighing on falling thirds and rising sixths in E minor.",
    1787711405342: "Two forceful chords, then a dark D-minor theme in the strings.",
    1787711405344: "A long orchestral introduction in D major before the soloist bursts in with fiery chords.",
    1787711405345: "A long oboe melody over the woodwinds before the violin enters.",
    1788489953372: "Urgent, pulsing minimalist rhythms and dense orchestral textures under the scientists' anxieties.",
    1788199516865: "Nixon's baritone aria, stuttering on the word “News” over a pulsing orchestra.",
    1788199516866: "A relentless woodblock pulse, with brass and percussion accelerating around it.",
    1788489953373: "The Chorus of Exiled Palestinians: slow, mournful choral lines over a pulsing orchestra.",
    1787711405959: "An orchestral picture of winter passing into spring, then the country folk welcoming the season.",
    1787711405960: "Adam and Eve's serene duet for soprano and bass, answered by the chorus.",
    1787711405961: "A formless C-minor opening: a unison note swelling from nothing and chromatic harmonies that never resolve.",
    1788489953197: "Manon's buoyant aria in gavotte rhythm, urging youth to enjoy life.",
    1787711405097: "A serene solo violin melody over harp and strings.",
    1788489953227: "Cabaret-style dance-band orchestration, with saxophone, banjo, and harmonium, for Brecht's songs.",
    1788199514251: "A soprano aria parodying Gounod's Jewel Song, swinging between mock despair and dazzling coloratura.",
    1788199514200: "Jazzy, syncopated rhythms and the tritone that opens “Maria”, which runs through the whole score.",
    1787792906340: "A tender, slow melody for muted strings and harp, interrupted by a sudden, brash outburst.",
    1787711405905: "Diabelli's own jaunty little C-major waltz, plain and repetitive.",
    1787711405907: "A dense double fugue in E-flat major.",
    1787711405912: "The prisoners, let out into the sunlight, sing a quiet, awestruck chorus that swells with hope.",
    1787711405012: "A gently rocking figure alternating E and D-sharp in A minor.",
    1787711405913: "A harsh, relentless double fugue with jagged leaps in all four strings.",
    1787711405914: "A dark B-minor plea for mercy, interrupted by distant military trumpets and drums.",
    1787711405915: "A long, high solo violin line floating above the choir and soloists.",
    1787711405926: "Quiet, pulsing repeated chords in the low register of the piano.",
    1787711405927: "A soft, singing rondo theme over a rippling left hand, with the pedal held to blur the sound.",
    1787711405931: "A bold leap and a fanfare of chords spanning the keyboard.",
    1787711405213: "A slow introduction that opens on a dissonant chord outside the home key, then a lively C-major theme.",
    1787711405214: "A gentle theme in the second violins, imitated by the other strings in turn.",
    1787711405217: "A long, lyrical melody in the strings, repeated by the woodwinds.",
    1787711405223: "A slow, weighty introduction before a vigorous D-major Allegro.",
    1787711405225: "A hushed, mysterious introduction in B-flat minor before the sudden, joyful Allegro.",
    1787711405241: "A lyrical melody over a persistent dotted rhythm in the accompaniment.",
    1787711405021: "A repeated long–short–short–long–long rhythm in the low strings, gradually spreading through the orchestra.",
    1787711405233: "A long, slow introduction with rising scales, then a dotted dance rhythm.",
    1787711405235: "A cheerful, direct F-major theme with no introduction.",
    1787711405253: "Woodwinds ticking in steady repeated notes like a metronome under a light string melody.",
    1787711405950: "Four soft timpani strokes, then a lyrical theme in the woodwinds.",
    1787711405951: "A jaunty hunting theme in 6/8 for the soloist.",
    1787711405953: "A sweet, singing violin melody over a flowing piano accompaniment.",
    1787711405954: "A bright, graceful rondo theme passed between piano and violin.",
    1787711405955: "The solo violin's unaccompanied chords in a slow introduction, then a fiery A-minor Presto.",
    1788489953357: "A lively mazurka with a strong accent on the second beat.",
    1787711405052: "Two high voices in close, gentle harmony over a flowing accompaniment.",
    1787711405138: "A snare drum repeating one rhythm under a single melody that grows louder as each instrument takes it up.",
    1787711405816: "Murmuring woodwinds and strings like a stream, then the sunrise in a broad melody.",
    1787711405817: "A long flute solo as Daphnis and Chloé act out the story of Pan and Syrinx.",
    1787711405819: "Shimmering, rapid repeated notes in the piano supporting a delicate melody.",
    1787711405820: "A B-flat tolling like a bell throughout, under dark chords.",
    1787711405829: "A lilting dance in 6/8 with dotted rhythms and piquant harmonies.",
    1787711405830: "Rapid, rippling patterns in perpetual motion.",
    1787711405834: "A slow, stately melody over a gently plucked accompaniment.",
    1787711405867: "A plaintive, folk-like melody in the bassoon over soft strings.",
    1787711405868: "The crowd's chorus pleading for Boris to take the throne, driven on by a police officer.",
    1787711405101: "Swirling strings and blasting brass: a witches' gathering.",
    1787711405120: "A stately theme alternating bars of 5/4 and 6/4, first on solo trumpet.",
    1787711405872: "A grand, hymn-like theme for full orchestra with bells.",
    1787792906320: "Unaccompanied violin, with fast arpeggios, octaves, and left-hand pizzicato.",
    1787711405385: "A bright, festive dance with flourishes for solo violin and clarinet.",
    1787711405386: "A gentle horn melody varied in turn by the orchestra.",
    1787711405394: "Solemn, chant-like melodies in woodwinds and strings, with bell sounds.",
    1787711405140: "A tender, flowing melody for strings.",
    1787711405395: "A booming theme for the Sultan in the trombones, then the solo violin's Scheherazade theme over harp.",
    1787711405400: "The solo violin's theme, then a bassoon solo telling the prince's tale.",
    1787711405141: "A non-stop chromatic scale in rapid notes, buzzing up and down.",
    1787792906347: "A clarinet imitating birdsong and a cello in high harmonics over the piano's repeating cycle of chords.",
    1787711405139: "A slow, soft march rhythm in the low instruments, growing to a thunderous climax with added brass.",
    1787711405055: "A quiet, mysterious introduction, then the bassoon's jaunty scherzo theme for the bewitched broom.",
    1788489953321: "Akhnaten's countertenor hymn over repeating arpeggios in the orchestra.",
    1787792906360: "Spoken text over repeating, hypnotic patterns.",
    1788489953320: "Slowly repeating arpeggios and chords building in layers.",
    1787711405734: "A grand, festive polonaise for the St. Petersburg ball in Act III.",
    1787711405735: "A lilting waltz with a lively chorus for the Act II ball.",
    1787711405172: "A sombre B-flat minor march on a Serbian folk song.",
    1787711405746: "Four horn notes, then the piano's thunderous chords under a sweeping string melody.",
    1787711405747: "A driving Ukrainian dance theme, with the piano racing to the finish.",
    1787711405715: "A menacing fanfare in horns and bassoons, the “Fate” motif.",
    1787711405719: "A melancholy oboe melody over pizzicato strings.",
    1788489953371: "Dark, eerie orchestral colours as Herman is haunted by the Countess's ghost.",
    1787711405759: "A gentle orchestral introduction, then the soloist enters with a lyrical D-major theme.",
    1787711405760: "A lively Russian folk dance, with the soloist playing rapid runs.",
    1788199515115: "A brass fanfare, then the chorus crying “Behold, the sea itself”.",
    1788199515071: "Rich, sustained string chords and Tallis's modal melody, echoing between two orchestras.",
    1787711405211: "A solo violin trilling and soaring without accompaniment, like a lark.",
    1787711404996: "A slow, mournful G-minor melody for strings over an organ bass.",
    1787711405167: "A low organ pedal, then trumpets rising C–G–C and thunderous timpani.",
    1788489953368: "Fast, witty conversational writing as the Composer and the household staff argue backstage.",
    1788199512489: "Shimmering high chords in celesta, flutes, and harp for the silver rose.",
    1788199512669: "A bold, sweeping E-flat theme for the hero in horns and cellos.",
    1788199512531: "Elektra's anguished cry of recognition, then a tender, soaring melody.",
    1788199512490: "A sinuous, exotic dance that grows faster and more frenzied.",
    1788199512713: "Soft, irregular rhythms in the strings like a failing heartbeat.",
    1787711405408: "Thunder and the rainbow bridge: a majestic brass theme climbing to Valhalla.",
    1787711405409: "A graceful, lilting dance for the apprentices.",
    1787711405410: "A pompous C-major march theme for the Mastersingers.",
    1787711405411: "Siegmund's tender tenor song of spring over lush strings.",
    1787711405415: "Timpani strokes and a solemn procession of leitmotifs.",
    1787711405416: "Rising horn calls and a flowing river theme.",
    1787711405203: "The familiar wedding march for chorus.",
    1787711405204: "A brilliant, festive fanfare-like theme for full orchestra.",
    1787711405421: "A slow, unaccompanied Communion theme in the strings and winds.",
    1787711405423: "A long, sustained trumpet note, then a noble prayer theme.",
    1787711405424: "Siegfried's forging song, with hammer blows on the anvil.",
    1787711405425: "Rustling strings and bird calls in the woodwinds.",
    1787711405426: "The pilgrims' chorale on clarinets, horns, and bassoons.",
    1787711405429: "A male chorus sings the slow, reverent pilgrims' hymn.",
    1787711405412: "The Steersman's nautical song, sung sleepily on watch.",
    1787711405413: "Stormy strings and the horn's Dutchman motif in hollow fifths.",
    1787792906326: "Brünnhilde urges Sieglinde to flee, with the redemption theme soaring in the orchestra.",
    1787711405465: "A grand, festive opening of chords and dance rhythms.",
    1787711405469: "A defiant, hammering chordal accompaniment under the singer's bitter declaration.",
    1787711405470: "A heavy, sombre song ending with a long piano postlude.",
    1787711405479: "A simple, tender melody over gentle broken chords.",
    1787711405480: "Frantic, agitated triplet runs in D minor.",
    1787711405464: "Short, contrasting waltzes and dances for piano.",
    1787711405488: "An orchestral chord, a cascade of piano chords, then the oboe's plaintive A-minor theme.",
    1787711405491: "A delicate dialogue between piano and orchestra in F major.",
    1787711405348: "Trumpets and horns in a bold fanfare, then a lively, spring-like theme.",
    1787711405350: "A vigorous D-minor scherzo with contrasting trios.",
    1787711405011: "A long, slow, stepwise melody in the strings, building to a searing climax.",
    1788199516961: "A lilting, nostalgic soprano melody over a gentle orchestral accompaniment.",
    1788489953317: "A short, wistful aria for mezzo-soprano.",
    1788199513453: "Lush, bittersweet melodies with sudden grotesque interjections.",
    1788199513407: "A distant cornet fanfare and a snare drum, then a playful march.",
    1787711405130: "The narrator's voice and Peter's cheerful theme in the strings.",
    1787711405131: "A heavy, stomping march in E minor for strings and brass.",
    1788199513545: "A jaunty, grotesque march with brass.",
    1788199513177: "A rocking 5/8 rhythm in the harp and low strings, like oars on dark water.",
    1787711405137: "A lush, romantic D-flat major melody: Paganini's theme turned upside down.",
    1787792906355: "Short melodic cells repeated and overlapping over a pulsing high C.",
    1788199515443: "A long, floating soprano melody over a gentle accompaniment with flute.",
    1788489953362: "Dramatic choral writing and brass fanfares.",
    1787711405103: "A serene, singing clarinet melody in D major.",
    1787711406007: "A slow introduction with an oboe solo, then rapid, chattering strings.",
    1787711406008: "A gentle tenor aria over muted strings.",
    1787711406009: "A lively chorus with Turkish percussion: triangle, cymbals, and bass drum.",
    1787711406010: "A fast overture with Turkish percussion bursting in.",
    1787711406033: "A turbulent tenor aria with fast runs, depicting a raging sea.",
    1787711406034: "A grand, energetic D-major overture.",
    1787711405115: "A bright rondo moving from A minor to A major, with janissary-like rhythms.",
    1787711406046: "A graceful A-major theme in siciliana rhythm, the subject of variations.",
    1787711406073: "An agitated violin theme in G minor over throbbing violas.",
    1787711406074: "A gentle E-flat major theme with repeated notes.",
    1788489953374: "The suite's famous “orchestral sneeze” and the colours of the cimbalom.",
    1788199515740: "A bold orchestral opening, then the soloist with Spanish rhythms and melodies.",
}

DUPES = [1787711405877, 1787711405879]      # "Organ Symphony" = Saint-Saëns Symphony No. 3

if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    ids = C.anki("findNotes", query='"deck:Classical Music" Kind:')
    ns = []
    for k in range(0, len(ids), 400):
        ns += C.anki("notesInfo", notes=ids[k:k + 400])
    ch = []
    seen = set()
    for n in ns:
        F = n["fields"]
        key = (C.plain(F["Work"]["value"]), C.plain(F["Composer"]["value"]))
        new = {}
        if key in DESC and not C.plain(F["Description"]["value"]):
            new["Description"] = DESC[key]
            seen.add(key)
        if n["noteId"] in LISTEN and not C.plain(F["Listen"]["value"]):
            new["Listen"] = LISTEN[n["noteId"]]
        if new:
            ch.append((n, new))
    missing = set(DESC) - seen
    print("notes to update:", len(ch), "| descriptions matched:", len(seen), "of", len(DESC), "| unmatched:", sorted(missing))
    print("listen lines:", sum(1 for n, new in ch if "Listen" in new), "of", len(LISTEN))
    if "--apply" in sys.argv:
        json.dump([{"nid": n["noteId"], "fields": {k: n["fields"][k]["value"] for k in new}} for n, new in ch],
                  open("backups/cm_content_0928_%s.json" % time.strftime("%Y%m%d_%H%M"), "w", encoding="utf-8"), ensure_ascii=False)
        for n, new in ch:
            C.anki("updateNoteFields", note={"id": n["noteId"], "fields": new})
        cards = [c for n in C.anki("notesInfo", notes=DUPES) for c in n["cards"]]
        C.anki("suspend", cards=cards)
        C.anki("addTags", notes=DUPES, tags="Music::dupe-suspended")
        print("applied", len(ch), "notes; suspended", len(cards), "duplicate cards")
