# -*- coding: utf-8 -*-
"""Listen lines: what is audible, in the order you notice it.

Rule for writing these: nothing here may be knowable from the title. No dates, no
history, no "one of his greatest" -- Description already carries that. Forces,
texture, tempo, key colour, and the one identifying gesture. Written to be
discriminative, so the line separates the piece from its nearest neighbours in
the deck rather than merely describing it.

Matched on (composer, work, nickname, movement-fragment); "" matches anything, and
the most specific match wins.
"""
L = [
 # ---- Beethoven ----
 ("beethoven","symphony no 5","","mvt i","Three shorts and a long, unharmonised and fortissimo, then every bar of the movement built from that one cell. C minor, terse, almost no tune."),
 ("beethoven","symphony no 5","","mvt ii","A♭ major: warm walking theme low in violas and cellos, broken up by a blazing brass fanfare in C that keeps returning."),
 ("beethoven","symphony no 5","","mvt iii","Scherzo creeping up from the double basses, then horns bark the short-short-short-long rhythm; ends in a long dark crescendo that runs straight into the finale without stopping."),
 ("beethoven","symphony no 5","","mvt iv","C major blaze with trombones and piccolo newly added; the scherzo's ghost creeps back in the middle, then a hammered coda that refuses to end."),
 ("beethoven","symphony no 3","eroica","mvt i","Two blunt E♭ chords, then a cello theme that stumbles onto a foreign C♯. Enormous — this movement alone outlasts a whole Haydn symphony. Listen for the horn entering a bar early, over the wrong chord, before the recapitulation."),
 ("beethoven","symphony no 3","eroica","mvt ii","Funeral march: C minor tread over a muffled drumming bass, oboe carrying the tune; a bright C major trio, then the theme returns broken into gasping fragments."),
 ("beethoven","symphony no 3","eroica","mvt iii","Light, fast, whispered scherzo; three horns in the trio playing hunting calls."),
 ("beethoven","symphony no 3","eroica","mvt iv","Variations on a bare skeleton of a bass line, including a full fugue, then a slow hymn-like statement before a sudden Presto."),
 ("beethoven","symphony no 6","pastoral","mvt i","Drone bass, birdlike woodwind, one short figure repeated unhurriedly for minutes on end. F major, and nothing develops — deliberately."),
 ("beethoven","symphony no 6","pastoral","mvt iii","Rustic dance; a bassoon that can only manage three notes, and an oboe entering off the beat like a village band."),
 ("beethoven","symphony no 6","pastoral","mvt iv","The one violent stretch: timpani, trombones, piccolo, tremolo strings — a storm, played without a break into the finale."),
 ("beethoven","symphony no 6","pastoral","mvt v","Pipe tune in clarinet then horn over a rocking 6/8, growing into a broad hymn of thanks."),
 ("beethoven","symphony no 9","choral","mvt i","Bare open fifths, as though the orchestra were tuning, out of which the D minor theme assembles itself. Granitic; the opening returns as a full-orchestra unison."),
 ("beethoven","symphony no 9","choral","mvt ii","Molto vivace scherzo, driving and fugal; the timpani, tuned in octaves, punch in as a solo voice."),
 ("beethoven","symphony no 9","choral","mvt iii","Two slow themes alternating in B♭, the only sustained calm in the work; a famous fourth-horn solo."),
 ("beethoven","symphony no 9","choral","mvt iv","Shrieking dissonance, then cellos and basses recite wordlessly; the Ode to Joy tune enters low, unaccompanied, and is built up by stages to full chorus. Later a Turkish march with cymbals, triangle and bass drum under a solo tenor."),
 ("beethoven","piano sonata no 14","moonlight","mvt i","Unbroken triplet arpeggios in C♯ minor under a bare dotted melody, quiet and pedal-blurred from first bar to last."),
 ("beethoven","piano sonata no 14","moonlight","mvt ii","Short, mild D♭ major Allegretto — the flower between two abysses."),
 ("beethoven","piano sonata no 14","moonlight","mvt iii","Presto agitato: broken chords rocketing upward into hammered sforzando chords. This, not the first movement, is the real finale."),
 ("beethoven","piano sonata no 14","moonlight","","Unbroken triplet arpeggios in C♯ minor under a bare dotted melody; quiet and pedal-blurred, with no fast music until the third movement."),
 ("beethoven","piano sonata no 8","pathetique","mvt i","Heavy dotted C minor chords marked Grave, then a scurrying Allegro over drumming left-hand octaves; the Grave keeps breaking back in, which sonata form is not supposed to allow."),
 ("beethoven","piano sonata no 8","pathetique","mvt ii","Adagio cantabile: an even, hymn-like A♭ melody in the middle of the keyboard, almost unornamented."),
 ("beethoven","piano sonata no 8","pathetique","mvt iii","Rondo with a lilting, wistful C minor refrain; light and fast."),
 ("beethoven","piano concerto no 5","emperor","mvt i","One orchestral chord, then the piano answers with a sprawling improvisatory flourish — three times over, before the movement proper begins. E♭, martial, very long."),
 ("beethoven","piano concerto no 5","emperor","mvt iii","Rondo: the piano leaps in with a bounding, syncopated dance; the coda thins to piano and timpani alone."),
 ("beethoven","choral fantasy","","","Piano alone and improvising, then orchestra, then — unexpectedly for a piano piece — soloists and chorus, on a tune that is plainly a first draft of the Ode to Joy."),
 # ---- Mozart ----
 ("mozart","eine kleine nachtmusik","","mvt i","Unison rocket figure up and back down, G major, strings only, brisk and perfectly symmetrical."),
 ("mozart","eine kleine nachtmusik","","mvt ii","Romanze: gentle rondo in C with a scampering staccato middle section."),
 ("mozart","eine kleine nachtmusik","","mvt iii","Very short minuet, sharply accented, with a smooth trio."),
 ("mozart","eine kleine nachtmusik","","mvt iv","Fast chattering rondo, phrases flicking between loud and quiet."),
 ("mozart","symphony no 41","jupiter","","Alternating loud martial C major tutti and quiet lyrical answer in the opening bars; the finale piles five themes into one fugue at once."),
 ("mozart","symphony no 35","haffner","","Festive D major opening on a leaping unison octave figure, no exposition repeat, trumpets and drums throughout."),
 ("mozart","requiem","","introit","Dark low wind colour — bassoons and basset horns — chorus entering low and staggered, then a lone soprano on 'Te decet hymnus'."),
 ("mozart","requiem","","kyrie","Brisk double fugue for chorus, ending on a bare unharmonised chord."),
 ("mozart","requiem","","dies irae","Short, fast, hammering chorus over plunging strings; over in barely a minute and a half."),
 ("mozart","requiem","","tuba mirum","Solo trombone duets with the bass soloist, then tenor, alto and soprano enter in turn and combine."),
 ("mozart","requiem","","rex tremendae","Stabbing dotted chorus entries on the word 'Rex'; collapses to a hushed 'salva me'."),
 ("mozart","requiem","","lacrimosa","Rising-and-falling string sighs in a slow 12/8, chorus quiet then swelling to a cry. Mozart's own hand stops after eight bars."),
 ("mozart","requiem","","sanctus","Bright D major, very brief, running straight into the 'Osanna' fugue."),
 ("mozart","die zauberflote","","overture","Three solemn held chords, then a light, quick fugal Allegro in E♭; the three chords return in the middle."),
 ("mozart","die zauberflote","","vogelfanger","Strophic folk-like tune for baritone with a panpipe answering at the end of each verse."),
 ("mozart","die zauberflote","","holle rache","Furious D minor coloratura soprano, staccato leaps climbing twice to a high F — the highest note in standard opera."),
 ("mozart","die zauberflote","","isis","Very slow, very low bass solo with male chorus answering; hushed and ceremonial."),
 ("mozart","die zauberflote","","madchen","Bright, simple, singsong baritone tune accompanied by glockenspiel."),
 ("mozart","die zauberflote","","papagena","Stammered 'Pa-pa-pa' duet, fast and comic, two voices tripping over each other."),
 ("mozart","don giovanni","","overture","Grim slow D minor chords — the stone statue's music — then a bustling D major Allegro that never resolves the darkness."),
 ("mozart","don giovanni","","champagne","Headlong baritone patter, orchestra scrambling to keep up; under two minutes."),
 ("mozart","don giovanni","","ma qual mai","Shocked, halting ensemble over tremolo strings, immediately after the killing."),
 ("mozart","le nozze di figaro","","overture","Whispered rushing unison in D, no slow introduction at all, breathless from the first bar and very short."),
 ("mozart","le nozze di figaro","","non piu andrai","Mock-heroic military march for baritone with trumpets and drums."),
 ("mozart","le nozze di figaro","","voi che sapete","Gentle, slightly breathless mezzo aria over a plucked, guitar-like accompaniment."),
 ("mozart","la clemenza di tito","","parto","Mezzo line with an obbligato clarinet winding around the voice as an equal partner."),
 # ---- Tchaikovsky ----
 ("tchaikovsky","1812 overture","","","Opens with low unaccompanied violas and cellos as a Russian hymn; La Marseillaise cut through by Russian themes, then cannon, carillon and brass band."),
 ("tchaikovsky","romeo and juliet","","","Solemn hushed woodwind chorale, then a violently syncopated fight-music Allegro, then a broad soaring love theme."),
 ("tchaikovsky","swan lake","","introduction","Oboe over tremolo strings with the swan theme in B minor, building to a brass outburst."),
 ("tchaikovsky","swan lake","","waltz","Long sweeping A major waltz with full orchestral swing; the big set-piece dance."),
 ("tchaikovsky","swan lake","","scene","The swan theme proper: plaintive oboe over rippling harp and strings, B minor."),
 ("tchaikovsky","swan lake","","little swan","Two bassoons chugging staccato under a quick stepping oboe duet — tiny and precise."),
 ("tchaikovsky","swan lake","","dance of the swans","Flowing string melody with harp, broader and warmer than the little swans."),
 ("tchaikovsky","swan lake","","march","Crisp brass-led ceremonial march."),
 ("tchaikovsky","swan lake","","","Plaintive oboe swan theme over rippling harp in B minor; lavish string writing and a prominent violin solo."),
 ("tchaikovsky","the nutcracker","","overture","Scored with no cellos or basses at all — unusually light, high and glittering."),
 ("tchaikovsky","the nutcracker","","march","Brass fanfare answered by skipping strings, toy-soldier crispness."),
 ("tchaikovsky","the nutcracker","","sugar plum","Celesta — a bell-like keyboard — picking out the tune over pizzicato strings and bass clarinet."),
 ("tchaikovsky","the nutcracker","","trepak","Very fast Russian dance with tambourine, accelerating to a stamping finish in under ninety seconds."),
 ("tchaikovsky","the nutcracker","","arab","Drowsy swaying G minor over a drone, muted strings and tambourine."),
 ("tchaikovsky","the nutcracker","","chinese","Piccolo and flute chirping high over a plodding bassoon ostinato."),
 ("tchaikovsky","the nutcracker","","mirliton","Three flutes in close harmony, light and reedy, with a brassy minor middle section."),
 ("tchaikovsky","the nutcracker","","waltz of the flowers","Harp cadenza, then horns announce the waltz theme; the grandest number in the suite."),
 ("tchaikovsky","the nutcracker","","pas de deux","A slow descending scale in the strings, plain and enormous, building to a full-orchestra climax."),
 ("tchaikovsky","the sleeping beauty","","introduction","Snarling brass Carabosse music, then the Lilac Fairy's gentle curling theme."),
 ("tchaikovsky","the sleeping beauty","","garland","Broad spacious waltz in A, warmer and slower-turning than the Nutcracker's."),
 ("tchaikovsky","the sleeping beauty","","pas de quatre","Delicate short character variations, harp and solo winds."),
 ("tchaikovsky","symphony no 5","","mvt i","Low clarinets intone a bare 'fate' motto, then a limping E minor Allegro; the motto returns in every movement."),
 ("tchaikovsky","symphony no 5","","mvt ii","Long solo horn melody over hushed strings — the most famous horn solo in the symphonies — twice interrupted by the fate motto blaring out."),
 ("tchaikovsky","symphony no 5","","mvt iii","A waltz where the scherzo should be, elegant and slightly weary; the motto creeps in at the end on clarinet and bassoon."),
 ("tchaikovsky","symphony no 5","","mvt iv","The fate motto turned major and triumphant in the slow introduction, then a driving finale and a march-like blaze to close."),
 ("tchaikovsky","symphony no 6","pathetique","mvt i","Bassoon alone in the depths, then a restless B minor Allegro; a famous soaring second theme, and a bassoon marked to play as quietly as possible before a shattering tutti."),
 ("tchaikovsky","symphony no 6","pathetique","mvt ii","A waltz in five beats to the bar, so it never quite settles; lilting and lopsided."),
 ("tchaikovsky","symphony no 6","pathetique","mvt iii","Scurrying strings out of which a brass march assembles itself, ending brilliantly and loudly — which is not the end of the symphony."),
 # ---- Schubert ----
 ("schubert","symphony no 8","unfinished","mvt i","Low unison cellos and basses alone in B minor, then shivering strings under an oboe-and-clarinet melody; the second theme is a famous cello tune over syncopated accompaniment."),
 ("schubert","symphony no 8","unfinished","mvt ii","Serene E major, descending pizzicato bass under strings, with a long plaintive clarinet solo. The symphony stops after this."),
 ("schubert","symphony no 9","great","mvt i","Unaccompanied horns call, then a very long Andante introduction before the Allegro; enormous in scale, and the horn theme returns in full brass at the end."),
 ("schubert","symphony no 9","great","mvt ii","Walking A minor oboe tune over a tramping accompaniment; a sudden violent silence, then a hushed restart."),
 ("schubert","symphony no 9","great","mvt iii","Big muscular scherzo with a broad Austrian-dance trio."),
 ("schubert","symphony no 9","great","mvt iv","Relentless galloping triplets, with a repeated four-note hammered figure lifted from the Ode to Joy."),
 ("schubert","piano quintet","trout","mvt i","Piano quintet with a double bass instead of a second violin, so the bottom is unusually dark against bright piano. A major, expansive, rippling."),
 ("schubert","piano quintet","trout","mvt ii","Three paired themes, each stated and then repeated a third higher; unhurried and songlike."),
 ("schubert","piano quintet","trout","mvt iii","Short, sharply accented, very fast scherzo."),
 ("schubert","piano quintet","trout","mvt v","Hungarian-flavoured finale in 2/4, the violin tune answered in unison octaves."),
 # ---- Chopin / Liszt ----
 ("chopin","nocturne op 9 no 2","","","E♭ major, lilting 12/8 over a wide left-hand waltz bass; the melody returns each time more heavily ornamented, ending in a rippling cadenza."),
 ("chopin","nocturne op 27 no 2","","","D♭ major, slower and more sensuous than Op. 9 No. 2, the melody often doubled in thirds and sixths over a very wide rocking bass."),
 ("chopin","polonaise","heroic","","A♭ major, hammering dotted polonaise rhythm; the trio is built on descending left-hand octaves, fast and loud."),
 ("chopin","polonaise","military","","A major, short, brassy and square — a march you could parade to, far plainer than the Heroic."),
 ("chopin","waltz","minute","","D♭ major, a whirling figure that spins in a circle and never lands; fast, light, barely over a minute."),
 ("liszt","transcendental etudes","","","Extreme piano virtuosity as the subject itself: leaps, double notes, tremolo and rapid figuration, each study built on a single difficulty."),
 # ---- Brahms, Mendelssohn, Schumann, Dvorak, Haydn, Stamitz ----
 ("brahms","symphony no 3","","mvt i","Three-chord wind motto, then a sweeping F major theme falling through the strings; passionate but compact."),
 ("brahms","symphony no 3","","mvt ii","Quiet hymn-like clarinet and bassoon phrase answered by strings."),
 ("brahms","symphony no 3","","mvt iii","Poco allegretto: the famous melancholy C minor cello melody over a gently rocking accompaniment, later taken by the horn."),
 ("brahms","symphony no 3","","mvt iv","Muttering F minor unison opening, a fierce middle, then — unusually — the symphony fades out quietly on the first movement's motto."),
 ("brahms","requiem","german","mvt i","No violins at all, so the sound is dark and bottom-heavy; the chorus enters low and slow on 'Selig sind'. German text, not the Latin Mass."),
 ("brahms","requiem","german","mvt ii","Slow heavy tread in 3/4 — a funeral march in dance metre — building to a bright fast fugal 'Die Erlöseten'."),
 ("brahms","requiem","german","mvt iii","Baritone solo answered by chorus, ending in a long fugue held over a single sustained pedal D in bass and timpani."),
 ("brahms","requiem","german","mvt iv","Gentle flowing E♭ chorus in 3/4, the most immediately lyrical movement."),
 ("brahms","requiem","german","mvt v","Soprano solo over a quiet chorus, consoling; the only movement with a soprano."),
 ("mendelssohn","symphony no 3","scottish","mvt i","Dark misty A minor introduction on low winds and violas; the Allegro is stormy, and the introduction returns to close it."),
 ("mendelssohn","symphony no 3","scottish","mvt ii","Fast light F major with a pentatonic, bagpipe-flavoured clarinet tune over a drone."),
 ("mendelssohn","symphony no 3","scottish","mvt iii","Slow A major song for strings, broken up by a grim funeral-march rhythm in the winds and drums."),
 ("schumann","symphony no 3","rhenish","mvt i","Buoyant E♭ theme with a cross-rhythm pulling against the bar, horns prominent."),
 ("schumann","symphony no 3","rhenish","mvt iii","Gentle unassuming intermezzo, quiet and songlike."),
 ("schumann","symphony no 3","rhenish","mvt iv","Solemn brass chorale in E♭ minor, trombones leading — the cathedral movement, and it is the fourth of five."),
 ("schumann","symphony no 3","rhenish","mvt v","Bright bustling finale; the chorale returns in the brass near the end."),
 ("dvorak","symphony no 9","new world","mvt i","Slow Adagio opening, then a horn call built on a falling minor third with a flattened seventh; driving E minor, folk-flavoured tunes in flutes and oboes."),
 ("dvorak","symphony no 9","new world","mvt ii","Solemn wind chords, then the famous long cor anglais solo — English horn, and nothing else in the repertoire sounds quite like it — in D♭."),
 ("dvorak","symphony no 9","new world","mvt iii","Hard-driving triangle-and-timpani scherzo with abrupt gear changes; the first movement's theme intrudes."),
 ("dvorak","symphony no 9","new world","mvt iv","Brass and horns blaze a march-like theme in E minor; the themes of all three earlier movements return, and the last chord fades rather than stops."),
 ("haydn","symphony no 104","london","mvt i","Stern unison D minor fanfare as the slow introduction, then a sunny D major Allegro."),
 ("haydn","symphony no 94","surprise","mvt ii","Nursery-simple tune played twice, the second time even softer — then a sudden fortissimo chord with full timpani. That chord is the whole point."),
 ("stamitz","symphony","","","Early Mannheim symphony: a long orchestral crescendo, tremolo strings, abrupt loud-soft contrast and independent wind writing — the machinery of the classical symphony being assembled."),
 # ---- Vivaldi, baroque and earlier ----
 ("vivaldi","the four seasons","","spring","Solo violin over ripieno strings, E major; birdsong in two or three violins at once, then a murmuring-brook accompaniment and a thunderstorm."),
 ("vivaldi","the four seasons","","summer","Languid oppressive opening that keeps stalling, a cuckoo cadenza, and a furious storm finale in rushing unison semiquavers."),
 ("vivaldi","the four seasons","","winter","Shivering repeated chords piling up one instrument at a time, chattering teeth in the solo violin; the slow movement is pizzicato raindrops under a smooth violin line."),
 ("couperin","pieces de clavecin","","","Solo harpsichord, heavily ornamented with trills and mordents, in dance suites with picturesque titles rather than movement numbers."),
 ("gabrieli","sonata pian e forte","","","Two spaced brass-and-viol choirs answering each other across a church, with the words piano and forte printed in the parts — written dynamics, apparently for the first time."),
 ("dowland","lachrimae","","","Solo lute or viol consort, and a falling four-note teardrop figure opening every piece; deliberately melancholy throughout."),
 ("tallis","spem in alium","","","Forty independent voices, eight choirs of five, entering one at a time and eventually all together; the sound moves physically around the room."),
 ("byrd","great service","","","Anglican service music in English, full choir in expansive counterpoint, far grander than his short services."),
 ("weelkes","o care","","","English madrigal: sharp dissonance and word-painting, with a sudden bright fa-la-la refrain against the gloom."),
 ("palestrina","canticum","","","Unaccompanied Latin polyphony, smooth stepwise lines, every dissonance resolved — the model of Counter-Reformation clarity."),
 ("josquin","missa pange lingua","","","Four voices working a plainchant hymn through paired imitation, each phrase of the tune handed between voices."),
 ("du fay","missa l homme arme","","","Cantus firmus Mass: a secular tune held in immensely long notes in the tenor while the other voices move freely around it."),
 ("machaut","messe de notre dame","","","Four-voice Mass by a single composer to a single plan; rhythmically angular, harsh to modern ears, with isorhythmic tenor lines."),
 ("leonin","magnus liber","","","Two voices: plainchant held in very long drones beneath one florid upper line — organum, the oldest polyphony in the deck."),
 ("hildegard","ordo virtutum","","","A single unaccompanied female line with extraordinarily wide leaps and long melismas; no polyphony, no instruments."),
 ("blow","venus and adonis","","","Short English court masque-opera: continuo-accompanied recitative and dance, the direct model for Dido and Aeneas."),
 ("peri","euridice","","","Solo voice over a bare sustained continuo, following speech rhythm rather than metre — recitative before opera had anything else."),
 ("gay","the beggar s opera","","","Spoken dialogue between plain popular ballad tunes with light accompaniment; no recitative and no virtuosity."),
 # ---- late romantic, national, twentieth century ----
 ("mahler","symphony no 1","titan","","A high A held across the whole string section, then distant fanfares and a cuckoo call; the withdrawn Blumine movement is a gentle trumpet serenade."),
 ("mahler","symphony no 2","resurrection","","Ferocious tremolo C minor funeral opening; an alto solo, then a chorus entering almost inaudibly, and an ending with organ and offstage brass."),
 ("mahler","symphony no 8","thousand","","Organ and full chorus blazing 'Veni creator spiritus' from the first bar — double chorus, boys' choir, eight soloists, and no instrumental introduction at all."),
 ("wagner","tristan und isolde","","prelude","A rising cello phrase answered by a wind chord that refuses to resolve, over and over; slow, chromatic, with no stable key."),
 ("wagner","tristan und isolde","","liebestod","Soprano over a long orchestral swell that finally delivers the resolution withheld since the Prelude."),
 ("sibelius","finlandia","","","Snarling low brass, then a chorale-like hymn tune in the woodwinds over gentle strings; compact, and nationalist."),
 ("sarasate","zigeunerweisen","","","Solo violin in gypsy style: a free wailing slow rhapsody with slides and left-hand pizzicato, then a headlong fast dance."),
 ("wieniawski","violin concerto no 2","","","Romantic D minor showpiece: a long singing Romance as the middle movement, then a gypsy-rondo finale bristling with double stops and harmonics."),
 ("rodrigo","concierto de aranjuez","","","Classical guitar with orchestra; the slow movement is a long cor anglais melody answered by the guitar, Spanish and elegiac."),
 ("granados","goyescas","","","Solo piano, Spanish: strummed guitar-imitating chords, ornamental flourishes, and a slow dark 'nightingale' number."),
 ("albeniz","iberia","","","Dense, very difficult solo piano evoking Spanish regions — flamenco cross-rhythms, guitar strumming and copla-like tunes."),
 ("falla","el sombrero","","","Spanish ballet: sharp castanet and hand-clap rhythms, brassy jota and farruca dances, brilliant hard-edged orchestration."),
 ("villa","bachianas","","","Bach's counterpoint played with Brazilian tunes and rhythms; one piece is eight cellos with a soprano singing wordlessly high above them."),
 ("mascagni","cavalleria rusticana","","intermezzo","Short and purely orchestral: a warm string melody with harp and organ underneath, played on an empty stage."),
 ("mascagni","l amico fritz","","","Verismo lyricism: conversational vocal writing over warm strings, with a famous cherry duet as its set-piece."),
 ("leoncavallo","pagliacci","","","Tenor alone, breaking down in a halting, sobbing line over heavy strings — the clown putting on the costume."),
 ("ponchielli","la gioconda","","dance of the hours","Ballet music: a prim staccato woodwind tune gathering speed through four sections into a galloping finish."),
 ("catalani","la wally","","","A long soaring soprano farewell over sustained strings; late Italian lyricism with a near-Wagnerian orchestra."),
 ("boito","mefistofele","","","Bass devil against full chorus and brass; an enormous choral prologue in heaven before any drama begins."),
 ("puccini","la boheme","","","Conversational vocal lines rising suddenly into big lyrical arcs over rich warm strings; parallel-chord harmony, and a bustling street-crowd scene."),
 ("puccini","madama butterfly","","","Japanese pentatonic tunes and whole-tone colour woven through Italian lyricism; a humming offstage chorus and a long orchestral vigil."),
 ("puccini","tosca","","te deum","Three brutal unison chords open it; a bass villain's monologue set against an ecclesiastical procession with organ, bells and full chorus."),
 ("puccini","tosca","","vissi d arte","Soprano alone over hushed strings, slow and pleading — the drama simply stops for it."),
 ("puccini","tosca","","lucevan","Tenor over a solo clarinet melody, quiet and broken; the orchestra takes the tune when he cannot."),
 ("puccini","suor angelica","","","Soprano lament over shimmering strings and harp; an all-female cast, no male voices."),
 ("puccini","il tabarro","","","Dark muted orchestral flow imitating the river, with conversational verismo over a continuous instrumental current."),
 ("puccini","il trittico","","","Three one-act operas in a row — grim river melodrama, all-female convent tragedy, then outright comedy."),
 ("verdi","la traviata","","libiamo","Brindisi: a swinging 3/8 drinking song, soloists then full chorus, deliberately catchy."),
 ("verdi","la traviata","","prelude","Very high divided violins, thin and fragile, then a broad warm melody — the illness before the love."),
 ("verdi","la traviata","","un di felice","Tenor and soprano trade phrases, he ardent and she deflecting with light coloratura."),
 ("verdi","la traviata","","de miei bollenti","Tenor over agitated strings, fast-moving and short."),
 ("verdi","rigoletto","","donna e mobile","Jaunty swaggering tenor tune in 3/8 over a thumping accompaniment; impossible to forget, which is the plot point."),
 ("verdi","rigoletto","","rammentomi","The famous quartet: four characters singing four different things at once, two outside in the storm and two inside."),
 ("verdi","rigoletto","","zitti","Whispered scurrying male chorus, staccato and quiet throughout."),
 ("verdi","aida","","triumphal","Long straight trumpets on stage playing a stiff march fanfare, then full chorus and band."),
 ("verdi","aida","","dance","Exotic-flavoured ballet music: piccolo, harp and modal tunes over light percussion."),
 ("verdi","aida","","fuggiam","Soprano and tenor duet, urgent and pressing forward over agitated strings."),
 ("verdi","requiem","","requiem aeternam","Barely audible muted strings and hushed chorus, then a quiet unaccompanied passage — it opens as softly as the Dies Irae is loud."),
 ("verdi","requiem","","dies irae - lacrymosa","The mezzo begins a sobbing descending line, taken up by the other soloists and chorus; it ends very quietly."),
 ("verdi","requiem","","dies irae - ingemisco","Tenor solo, lyrical and frankly operatic, with a long-breathed melody."),
 ("verdi","requiem","","dies irae","Bass drum hammering on every beat, full chorus shrieking, brass shattering — the loudest music Verdi wrote, and it recurs through the work."),
 ("verdi","falstaff","","burla","Full-company fugue on 'everything in the world is a joke' — the opera ends with academic counterpoint played as comedy."),
 ("verdi","don carlos","","ella giammai","Bass king alone, brooding over low strings and a cello solo; slow and heavy."),
 ("verdi","un ballo","","eri tu","Baritone over a mournful cor anglais solo, turning from rage to grief."),
 ("verdi","simon boccanegra","","","Dark baritone-and-bass writing with unusually little tenor; sombre orchestral colour throughout."),
 ("verdi","attila","","","Early Verdi: square driving rhythms, loud unison chorus writing, oom-pah accompaniment."),
 ("verdi","i lombardi","","","Early Verdi: massed patriotic chorus, banda on stage, and a violin solo introducing the trio."),
 ("verdi","ernani","","overture","Short brisk early overture: brass fanfare, then a cantabile tune over an oom-pah bass."),
 ("verdi","la forza del destino","","overture","Six hammered unison brass notes — the fate motif — then a fast restless stitching-together of the opera's tunes."),
 ("verdi","luisa miller","","overture","Built almost entirely on one nervous fast-moving theme rather than a medley."),
 ("rossini","il barbiere di siviglia","","","Slow introduction, then an Allegro with a long mechanically stepped-up crescendo repeated twice — the Rossini crescendo — ending in a whipped-up stretta."),
 ("rossini","guillaume tell","","overture","Five cellos alone, then a storm, then a cor anglais pastoral with flute — and finally the galloping trumpet cavalry march."),
 ("paisiello","il barbiere","","","Pre-Rossini opera buffa: lighter, thinner scoring and short symmetrical phrases, with no Rossini crescendo."),
 ("bizet","les pecheurs","","overture","Flute and harp over shimmering divided strings, modal and languid — exotic colour rather than a tune-medley."),
 ("halevy","la juive","","","Grand opéra: huge choral tableaux, brass bands, ceremonial processions, five acts."),
 ("spontini","la vestale","","","Severe, marble-like French classical style: dotted ceremonial rhythms, heavy brass, declamatory vocal writing."),
 ("boieldieu","la dame blanche","","","French opéra comique: light, tuneful, Scottish-flavoured melodies with spoken dialogue between."),
 ("flotow","martha","","overture","Light German-French tunefulness; 'The Last Rose of Summer' turns up as a plain Irish melody."),
 ("nicolai","die lustigen weiber","","overture","Long hushed moonlit opening, then a bustling comic Allegro; German Romantic, Weber-ish scoring."),
 ("balfe","the bohemian girl","","","English ballad opera: plain strophic songs with simple accompaniment, aimed at the drawing room."),
 ("cornelius","der barbier von bagdad","","overture","Wagner-influenced chromatic harmony in a comic opera; rich scoring over a light plot."),
 ("messager","veronique","","overture","French operetta: brisk elegant waltz and polka tunes, light and transparent."),
 ("chabrier","le roi malgre lui","","","French comic opera with startlingly bold harmony and a famous fête polonaise."),
 ("cimarosa","il matrimonio segreto","","overture","Classical opera buffa overture, Mozart-adjacent: crisp, symmetrical, string-led, no trombones."),
 ("hoffmann","undine","","","Early German Romantic opera: supernatural water music, tremolo strings and chromatic harmony under simple song forms."),
 ("smyth","the wreckers","","overture","Big late-Romantic sea music: surging strings and a brass chorale — the Cornish coast in sound."),
 ("strauss","arabella","","","Lyric soprano writing over a huge but transparent orchestra, with Viennese waltz tunes recurring throughout."),
 ("strauss","capriccio","","","Conversational, almost chamber-textured; it opens with a string sextet played before the curtain rises."),
 ("strauss","die frau ohne schatten","","","Vast orchestra with celesta, glass harmonica and organ; shimmering fairy-tale colour and very high soprano lines."),
 ("shostakovich","symphony no 7","leningrad","","A long crescendo over an obsessively repeated snare-drum march figure — the same few bars restated a dozen times with more instruments each pass. An invasion built out of repetition."),
 ("britten","the turn of the screw","","","A chamber ensemble of thirteen players; a theme and fifteen variations threaded between the scenes, with a boy soprano and celesta."),
 ("britten","albert herring","","","Comic chamber opera for a small ensemble; recitative-heavy and spiky, parodying church and civic music."),
 ("britten","the rape of lucretia","","","Eight singers and twelve players, with two narrators commenting from outside the action in an austere idiom."),
 ("britten","curlew river","","","Church parable: an all-male cast processing in singing plainchant, seven players, no conductor, and a heterophonic texture drawn from Japanese noh."),
 ("britten","a midsummer night s dream","","","Sliding string glissandi for the wood, a countertenor Oberon with celesta and harp, boys' voices for the fairies."),
 ("britten","death in venice","","overture","Restless, unsettled orchestral writing, with gamelan-like percussion marking the boy Tadzio throughout."),
 ("orff","carmina burana","","","Pounding unison chorus over hammering percussion and pianos, with almost no counterpoint; medieval Latin text and deliberate, primitive repetition."),
 ("widor","organ symphony no 5","","toccata","Solo organ: rapid detached chords in the hands over a slow pedal melody in the feet, building to full organ."),
 ("gorecki","symphony no 3","sorrowful","","Very slow and very long, almost nothing but a rising canon in the low strings; a soprano enters after twenty-odd minutes. Repetition and stasis are the whole substance."),
 ("whitacre","alleluia","","","Unaccompanied chorus in dense, slowly shifting close harmony on a single word; clusters that resolve only gradually."),
 ("higdon","blue cathedral","","","Shimmering orchestral washes, bells and rubbed crystal glasses, a flute then a clarinet solo emerging; consonant and slow-moving."),
 ("cage","4 33","","","Silence. The performer produces no sound; what you hear is the room."),
 ("xenakis","pithoprakta","","","Fifty strings each playing an independent glissando, with wood-block and siren-like sweeps — a statistical mass of sound rather than melody."),
 ("stockhausen","gruppen","","","Three full orchestras with three conductors placed around the audience, each in its own tempo; sound audibly moves between them."),
 ("schaeffer","symphonie pour un homme seul","","","No instruments at all: recorded breathing, footsteps and voice, cut and spliced on tape — musique concrète."),
 ("takemitsu","november steps","","","Japanese shakuhachi and biwa set against Western orchestra, the two never blending; long silences and sliding, breathy attacks."),
 ("mcphee","tabuh","","","Two pianos, xylophone and bells imitating a Balinese gamelan: interlocking fast ostinati, cyclic and metallic."),
 ("hindemith","mathis der maler","","","Angular harmony built on fourths and fifths over old chorale tunes; the first movement works a medieval hymn in the trombones."),
 ("dallapiccola","il prigioniero","","","Twelve-tone writing used dramatically — three recurring row-based motifs, a huge orchestra and an offstage chorus."),
 ("nono","intolleranza","","","Twelve-tone writing with tape, shouted chorus and projections; deliberately harsh and fragmented."),
 ("zimmermann","die soldaten","","","Several scenes played simultaneously with jazz band, tape, organ and huge percussion — deliberate sensory overload."),
 ("ullmann","der kaiser von atlantis","","","Small ensemble with Weill-like cabaret irony, quoting Deutschland über alles and a Bach chorale."),
 ("einem","dantons tod","","","Neoclassical tonality with sharp ostinati and big declamatory choruses."),
 ("reimann","lear","","","Microtonal string clusters and extreme vocal range; the title role shouts and speaks as well as sings."),
 ("rihm","die eroberung von mexico","","","Percussion-dominated and spatially separated, with howling and whispering voices over sustained bands of noise."),
 ("sciarrino","luci mie traditrici","","","Extremely quiet and sparse — breath tones, tiny gestures, long silences — under a slow declaimed vocal line."),
 ("ruders","the handmaid s tale","","","Two sopranos as one character; 'Amazing Grace' and Lutheran chorale quoted against grinding dissonance."),
 ("turnage","greek","","","Jazz and punk inflection in an opera pit: saxophones, drum kit, blues-derived harmony, shouted English."),
 ("nyman","the man who mistook","","","Small ensemble in driving repetitive minimalist patterns, with Schumann's 'Ich grolle nicht' quoted as the still centre."),
 ("tavener","mary of egypt","","","Orthodox chant-derived drones, bells and long unison lines; static, ritual and resolutely consonant."),
 ("schafer","apocalypsis","","","Hundreds of performers distributed through and around the hall — whispering, processions and antiphonal choirs in space."),
 ("thomson","four saints","","","Plain hymn-and-march American diatonic writing set to Gertrude Stein's non-narrative text; deliberately artless."),
 ("macdowell","woodland sketches","","","Short simple character pieces for solo piano; 'To a Wild Rose' is the tiny gentle one."),
 ("czerny","school of velocity","","","Solo piano exercises as music: continuous fast scale and finger patterns, one figuration per study, harmonically plain."),
 ("kabalevsky","the comedians","","","Short brash circus-flavoured orchestral numbers; the Galop is a xylophone-and-brass sprint."),
 ("rautavaara","thomas","","overture","Slowly shifting tonal clusters and modal chant fragments over sustained strings."),
 ("schulhoff","flammen","","","Jazz rhythms and dance-band inflection inside an expressionist opera; saxophone and flatted blues harmony."),
 ("montemezzi","l amore dei tre re","","","Post-Wagnerian Italian: continuous orchestral flow, no set-piece arias, dark low brass."),
 ("adam","giselle","","","Light tuneful ballet score built on recurring character motifs; Act II is all misty tremolo strings and harp."),
 ("berlioz","requiem","","dies irae","Four separate brass bands at the corners of the hall plus sixteen timpani — the loudest single stroke in the repertoire."),
 ("berlioz","requiem","","rex tremendae","Massed brass and chorus, then sudden hushed unaccompanied singing — extremes with nothing in between."),
 ("berlioz","requiem","","lacrimosa","Swaying 9/8, the one movement with a sustained singable melody; it builds enormously."),
 ("berlioz","requiem","","offertoire","The chorus is confined to two alternating notes for the whole movement while the orchestra carries the fugue."),
 ("berlioz","requiem","","sanctus","Solo tenor high over divided women's voices, flutes and soft strings, then a fugal Hosanna."),
 ("halle","le jeu de robin","","","Medieval monophonic song and dance with spoken dialogue and repeated refrains; one line, no harmony."),
]
